// Generated by dts-bundle-generator v7.2.0

import { ReactElement } from 'react';

/**
 * datatype / form description (json-schema)
 */
export interface Schema {
	/**
	 * ID if the schema is a DB table or property
	 */
	ID?: string;
	/**
	 * parent if the schema is a DB table or property
	 */
	parent?: string;
	/**
	 * name if the schema is a DB table or property
	 */
	name?: string;
	/**
	 * json schema form widget (e.g. date)
	 */
	widget?: string;
	/**
	 * json schema type
	 */
	type: string;
	/**
	 * json schema title
	 */
	title?: string;
	/**
	 * if DB table, optional instance toString / ID label
	 */
	"dj-label"?: string;
	/**
	 * if property, foreign key reference
	 */
	ref?: string;
	/**
	 * if property, primary key position
	 */
	pkpos?: number;
	/**
	 * json schema object properties
	 */
	properties?: {
		[key: string]: Schema;
	};
	/**
	 * json schema additional properties
	 */
	additionalProperties?: Schema;
	/**
	 * json schema required object properties
	 */
	required?: string[];
	/**
	 * json schema array subschema
	 */
	items?: Schema;
	/**
	 * choices http endpoint
	 */
	choicesUrl?: string;
	/**
	 * choices http verb (POST is default)
	 */
	choicesVerb?: string;
	/**
	 * jsonata expression that transforms http result into choices
	 */
	jsonata?: string;
	/**
	 * function that allows transforming values to display names (e.g. localName)
	 */
	displayWith?: string;
	/**
	 * indicates that a property controls which form elements to show
	 */
	switch?: string;
	/**
	 * indicates which switch values makes this property input show up
	 */
	case?: string[];
	/**
	 * 2-dimensional layout array
	 */
	order?: (string | string[])[];
	/**
	 * widget layout info
	 */
	layout?: string;
	/**
	 * input css style
	 */
	style?: {
		[key: string]: string;
	};
	/**
	 * static choices provided
	 */
	choices?: any[];
	enum?: any[];
}
/**
 * widget data structure
 */
export interface Widget {
	/**
	 * card title
	 */
	title?: string;
	/**
	 * icon tooltip
	 */
	tooltip?: string;
	/**
	 * text / icon href
	 */
	href?: string;
	/**
	 * widget selector
	 */
	widget?: string;
	/**
	 * icon for text and icon widget
	 */
	icon?: string;
	/**
	 * container's kids
	 */
	children?: Widget[];
	/**
	 * table expression (alternative to query)
	 */
	expression?: string;
	/**
	 * button navigate expression
	 */
	navigate?: string;
	/**
	 * button print expression
	 */
	print?: string;
	/**
	 * container if render expression
	 */
	if?: string;
	/**
	 * show only for these roles
	 */
	roles?: string[];
	/**
	 * display expression
	 */
	display?: string;
	/**
	 * markdown expression
	 */
	context?: string;
	/**
	 * text for expansion and text widgets
	 */
	text?: string;
	/**
	 * query to use
	 */
	query?: string;
	/**
	 * db to query
	 */
	database?: string;
	/**
	 * expression that computes the query arguments
	 */
	arguments?: string;
	/**
	 * used by display widget to specify map icons
	 */
	icons?: {
		[key: string]: string;
	};
	/**
	 * markdown source
	 */
	markdown?: string;
	/**
	 * responsive toolbar
	 */
	fxHide?: string;
	/**
	 * custom widget style
	 */
	style?: {
		[key: string]: string;
	};
	/**
	 * properties for button / variable widgets
	 */
	properties?: {
		[key: string]: string;
	};
	/**
	 * custom form for create / button
	 */
	createSchema?: Schema;
	/**
	 * chart type
	 */
	chart?: "bar" | "line" | "doughnut" | "radar" | "polarArea";
}
/**
 * Button with an optional form that triggers an action
 */
export declare const Button: ({ widget }: {
	widget: Widget;
}) => JSX.Element;
/**
 * draw card and title and delegate to container
 */
export declare function Card({ widget }: {
	widget: Widget;
}): JSX.Element;
/**
 * chart that displays data with the help of metadata
 */
export function Chart({ widget }: {
	widget: Widget;
}): JSX.Element;
/**
 * container that draws kids as a list of layouts
 * also has the option of determining the display based on an expression
 */
export declare const Container: ({ widget }: {
	widget: Widget;
}) => JSX.Element;
/**
 * create a new record
 */
export declare const Create: () => JSX.Element;
/**
 * evaluate expression and use Value to display
 */
export declare const Display: ({ widget }: {
	widget: Widget;
}) => JSX.Element;
/**
 * Edit widget - switch for edit record / table
 */
export declare const Edit: () => JSX.Element;
/**
 * draw card and title and delegate to container
 */
export declare function Expansion({ widget }: {
	widget: Widget;
}): JSX.Element;
/**
 * draw an incon with hyperlink
 */
export declare function Icon({ widget }: {
	widget: Widget;
}): JSX.Element;
/**
 * component to dynamically render widgets specified in the layout
 *
 * TODO: this code will be replaced with the layout component e.g. react page
 */
export declare function Layout({ widget }: {
	widget: Widget;
}): ReactElement;
/**
 * widget to turn on layout edit mode
 *
 * TODO: activate react pages here
 */
export declare function LayoutEditSwitch(): JSX.Element;
/**
 * displays links to table, as well as all outgoing and incoming links
 */
export declare const Links: () => JSX.Element;
/**
 * load expression and display it using open streemap
 */
export declare function Map({ widget }: {
	widget: Widget;
}): JSX.Element;
/**
 * renders markdown.
 * The template can contain references to the
 * context via ${var}
 *
 * the context is the "normal" context with an optional key "context" that
 * is initialized with the result of a jsonata expression:
 *
 * user: current user
 * value: current record
 * context: jsonata result
 */
export declare const Markdown: ({ widget }: {
	widget: Widget;
}) => JSX.Element;
/**
 * page no longer renders toolbar and sidebar.
 * instead it only renders children in mat cards
 */
export declare const Page: ({ widget }: {
	widget: Widget;
}) => JSX.Element[] | undefined;
/**
 * toolbar search
 * styles taken from https://mui.com/material-ui/react-app-bar/#app-bar-with-search-field
 *
 * the table / database input is not added since we can do this
 * more conveniently on the table level
 */
export declare const Search: () => JSX.Element;
/**
 * table widget that renders
 *
 * query
 * jsonata
 * search
 * "all" table
 */
export declare const Table: ({ widget }: {
	widget: Widget;
}) => JSX.Element;
/**
 * text widget for icons / links / texts
 * delegate to Value
 */
export declare function Text({ widget }: {
	widget: Widget;
}): JSX.Element;
/**
 * toolbar widget
 */
export declare function Toolbar({ widget }: {
	widget: Widget;
}): JSX.Element;
/**
 * root node - check for dj-nav special case (query does not exist in catalog)
 */
export declare const TreeRoot: ({ widget }: {
	widget: Widget;
}) => JSX.Element;
/**
 * sets a session variable via a form
 */
export declare function Variable({ widget }: {
	widget: Widget;
}): JSX.Element;

export {};
